---
- name: Ensure ~/.local/bin directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: '0755'

- name: Install chezmoi to ~/.local/bin
  ansible.builtin.shell: |
    sh -c "$(curl -fsLS get.chezmoi.io)" -- -b {{ ansible_env.HOME }}/.local/bin
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ ansible_env.HOME }/.local/bin:{{ ansible_env.PATH }}"

- name: Add ~/.local/bin to PATH in ~/.zshrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    insertafter: EOF
    state: present

- name: Initialize chezmoi and apply dotfiles
  ansible.builtin.shell: |
    "{{ ansible_env.HOME }}/.local/bin/chezmoi init --apply jeremyspofford"
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env:PATH }}"
  become: false
